{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyN/uBK3wWwsu7S9/NgyjFKX"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["# Excepciones\n","Las excepciones son utilizadas para el manejo de errores. Cuando se trata de errores, en cuanto, menos tengamos mejor, sin embargo es cierto tambien que estos son inevitables siempre estamos propensos a encontrar un error o **Bug** dentro de nuestros programas.\n","\n","Conociendo esto y tomando en cuenta que los errores son parte del dia a dia del desarrollador, para evitar que nuestra aplicacion se cierre al momento de ejecutarla y la experiencia del usuario en nuestro sistema sea mala, vamos hacer uso de las excepciones."],"metadata":{"id":"RoLkN2w2gPyV"}},{"cell_type":"code","execution_count":null,"metadata":{"id":"RM1pjaxIf7OJ"},"outputs":[],"source":["#sintaxis\n","try:\n","  run this code\n","except:\n","    execute this code when there is an error\n","else:\n","    whitout errors? Run this code.\n","finally:\n","      always run this code"]},{"cell_type":"markdown","source":["##Ejemplo del error"],"metadata":{"id":"OhwS-Mt4gjgQ"}},{"cell_type":"code","source":["numberOne = 5\n","numberTwo = 1\n","numberTwo = '1'\n","\n","print(numberOne + numberTwo) #el tener un error directo en cosola significa nuestro programa se muriooooh"],"metadata":{"id":"KEQvcLrbgngN"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["#Aplicando try - except"],"metadata":{"id":"jgJzE-4sgsM-"}},{"cell_type":"code","source":["#try - Except\n","try:\n","  print(numberOne + numberTwo)\n","  print('no hay ningun error')\n","except:\n","    #se ejecutara si se produce una excepcion\n","    print('se ha producido un error')"],"metadata":{"id":"X9_GX1g6g0TY"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["# Aplicando Try - Except - Else"],"metadata":{"id":"25EPX5SJg3mZ"}},{"cell_type":"code","source":["#Try - Except - Else(opcional) - finally(opcional)\n","numberOne = 1\n","numberTwo = 2\n","#numberTwo = '2'\n","\n","try:\n","  print(numberOne + numberTwo)\n","  print('no hay ningun error')\n","except:\n","    print('se ha producido un error')\n","else:\n","    #se ejecutara si no se produce ninguna excepcion\n","\n","    print('la ejecucion continua correctamente')"],"metadata":{"id":"IlkvY-9_g4QP"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["# Aplicando Try - Except - Else - Finally"],"metadata":{"id":"yVEfTJbrhBK4"}},{"cell_type":"code","source":["try:\n","  print(numberOne + numberTwo)\n","  print('no hay ningun error')\n","except:\n","    print('se ha producido un error')\n","else:\n","    print('la ejecucion continua correctamente')\n","finally:\n","    #esto siempre se ejecuta\n","    print('la ejecucion sigue')"],"metadata":{"id":"5utz-kyOhB54"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["#Analizando tipos de errores"],"metadata":{"id":"1ZbosZMehHRk"}},{"cell_type":"code","source":["numberOne = 5 #si este digito\n","numberTwo = 1 #y este otro llegaran a estar mal escritos marcaria error\n","number = '1'\n","\n","print(numberOne + numberTwo)\n","\n","try:\n","  print(numberOne + numberTwo)\n","  print('no hay ningun error')\n","except TypeError:\n","    #se ejecuta unicamente si el error es en el tipo de dato\n","    print('se ha producido un error')\n","\n","#solucionando el error\n","try:\n","  print(numberOne + numberTwo)\n","  print('no hay ningun error')\n","except TypeError:\n","    print('hubo un error')\n","    print('pero ya lo arregle')\n","    fixOne = int(numberOne)\n","    fixTwo = int(numbertwo)\n","    print(fixOne + fixTwo)\n","\n","#hay muchos tipos de errores\n","try:\n","  print(numberOne + numberTwo)\n","  print('no hay nigun error')\n","except ValueError:\n","  print('Hubo un error')\n","\n","try:\n","  print(numberOne + numberTwo)\n","  print('no hay ningun error')\n","except TypeError:\n","    print('se ha producido un TypeError')\n","except ValueError:\n","    print('hubo un error de valor')"],"metadata":{"id":"FRRnFHq9hJCR"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["lo normal y correcto  es que nosotros sepamos que se esta ejecutando y en que estamos mal y el tipo de error que se pudiera cometer y solucionarlo con estos bloques de codigos"],"metadata":{"id":"MVr6197AhSVg"}},{"cell_type":"markdown","source":["#Captura del tipo de excepcion"],"metadata":{"id":"7D6PZATRhTWD"}},{"cell_type":"code","source":["numberOne = 5\n","numberTwo = 1\n","numberTwo = '1'\n","\n","try:\n","  print(numberOne + numberTwo)\n","  print('no hay ningun error')\n","except TypeError as e:\n","    print(e)\n","\n","  #asignamos el error ocurrido a una variable e imprimos la informacion de nuestro error\n","  #Esto funciona mayormente en vscode, trabajando desde colab tenemos esta informacion desde el"],"metadata":{"id":"-WpfzWldhcMp"},"execution_count":null,"outputs":[]}]}